name: Semantic Release
run-name: ${{ github.actor }} is automatically releasing 🚀

on:
  push:
    branches:
      - main
      - auto-release

jobs:
  release:
    permissions:
      contents: write
      pull-requests: write
      issues: write
    runs-on: windows-latest
    steps:
      - name: 'Generate token'
        id: generate_token
        uses: tibdex/github-app-token@v2
        with:
          app_id: ${{ secrets.BOT_APP_ID }}
          private_key: ${{ secrets.BOT_PRIVATE_KEY }}

      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ steps.generate_token.outputs.token }}

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "lts/*"

      - name: Install dependencies
        run: npm install

      - name: Install PSMSI module
        run: pwsh -Command "Install-Module -Name PSMSI -Force -Scope CurrentUser"

      - name: Install @semantic-release/git
        run: npm install --save-dev @semantic-release/git

      - name: Install @semantic-release/exec
        run: npm install --save-dev @semantic-release/exec

      - name: Run Semantic Release
        env:
          GH_TOKEN: ${{ steps.generate_token.outputs.token }}
        run: npx semantic-release

